# Configuração customizada para o Vault Helm Chart
# Ref: https://github.com/hashicorp/vault-helm/blob/main/values.yaml

server:
  # Habilitar Ingress se necessário
  ingress:
    enabled: false
    # hosts:
    #   - host: vault.example.com

  # Configuração de persistência (Standalone ou HA)
  dataStorage:
    enabled: true
    size: 10Gi
    # storageClass: standard

  # Modo de deploy (standalone é mais simples para labs)
  standalone:
    enabled: true

# Habilitar o UI do Vault
ui:
  enabled: true
  serviceType: ClusterIP
