# Configuração customizada para o Vault Helm Chart em k8s/vault
# Ref: https://github.com/hashicorp/vault-helm/blob/main/values.yaml

vault:
  server:
    # Habilitar Ingress seguindo o padrão superlab.app
    ingress:
      enabled: true
      hosts:
        - host: vault.superlab.app
          paths:
            - path: /
              pathType: Prefix

    dataStorage:
      enabled: true
      size: 10Gi

    standalone:
      enabled: true

  ui:
    enabled: true
    serviceType: ClusterIP
